[insert]
empty = { input = [], insert = 1, inner = [1] }
three = { input = [1, 2, 3], insert = 4, inner = [4, 1, 2, 3] }
duplicate = { input = [1, 1], insert = 1, inner = [1, 1, 1] }

[find]
empty = { input = [], equals = 3, inner = [] }
no-match = { input = [1, 2], equals = 3, inner = [1, 2] }
first = { input = [1, 2, 3], equals = 1, inner = [1, 2, 3], expected = 1 }
second = { input = [1, 2, 3], equals = 2, inner = [2, 1, 3], expected = 2 }
last = { input = [1, 2, 3], equals = 3, inner = [3, 1, 2], expected = 3 }
